### ISSUE TITLE
Class 'Locale' not found

### ISSUE THREAD

**Issue by webdesign7** [mpalourdio/MpaCustomDoctrineHydrator#1]
Hello,

just installed your module through composer but I get this error:

```
Fatal error: Class 'Locale' not found in C:\xampp\htdocs\directory\vendor\mpalourdio\mpa-custom-doctrine-hydrator\src\Factory\DateElementFactory.php on line 31
```

Any ideas ?
Thanks
Sergiu C.

**Comment by mpalourdio** [comment]
wow, sorry, i hadn't seen there were issues here. I had unchecked the 'watch' button :/
You have to install the php/intl extension. but I bet it's too late :D

I should add the extension as requirement in composer.json...

**Comment by mpalourdio** [comment]
Done here : https://github.com/mpalourdio/MpaCustomDoctrineHydrator/commit/0313010bde5839147fd12261e3c3c7f5c4e7c2d1
