### ISSUE TITLE
Notice: Undefined index: en_US_POSIX 

### ISSUE THREAD

**Issue by webdesign7** [mpalourdio/MpaCustomDoctrineHydrator#3]
Hello, 

Any ideas about this error?

Notice: Undefined index: en_US_POSIX in  /vendor/mpalourdio/mpa-custom-doctrine-hydrator/src/Factory/TimeElementFactory.php on line 31

Thanks
Sergiu

**Comment by mpalourdio** [comment]
I bet you have to add the config for this specific locale in `mpacustomdoctrinehydrator.config.{global,local}.php`

But IMO, en_US_POSIX is a default when no locale is defined in your dev. environment (=== null)

**Comment by mpalourdio** [comment]
Closed a no feedback. Feel free to re-open if needed
